apiVersion: apps/v1
kind: Deployment
metadata:
  name: staff-service
  labels:
    app: staff-service
spec:
  replicas: 2  # Number of pods to deploy
  selector:
    matchLabels:
      app: staff-service
  template:
    metadata:
      labels:
        app: staff-service
    spec:
      containers:
      - name: staff-service
        image: dhruv766/staff-service:1  # Replace with your actual Docker image
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: staff-service
spec:
  selector:
    app: staff-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer  # Expose the service using an external IP
