# Deployment for Staff-Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: staff-service
spec:
  replicas: 1 # Single replica
  selector:
    matchLabels:
      app: staff-service
  template:
    metadata:
      labels:
        app: staff-service
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: staff-service
          image: dhruv766/staff-service:final # Custom image for staff service
          ports:
            - containerPort: 3000 # Staff service listens on this port
          env: # Environment variables for configuration
            - name: FASTIFY_ADDRESS
              value: "0.0.0.0"
          resources: # Resource allocation
            requests:
              cpu: 1m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 256Mi
          startupProbe: # Initial health check
            httpGet:
              path: /health
              port: 3000
            failureThreshold: 5
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe: # Ready status probe
            httpGet:
              path: /health
              port: 3000
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe: # Ongoing health check
            httpGet:
              path: /health
              port: 3000
            failureThreshold: 5
            initialDelaySeconds: 3
            periodSeconds: 3
---
# Service for Staff-Service
apiVersion: v1
kind: Service
metadata:
  name: staff-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: staff-service
---
